### PR TITLE
output a ZIP with JSON and CSV versions of all outputs

### LINKED ISSUE #27: feat: compress all output json files into a `archive.zip`
In the dashboard, we wish to allow users to download the input datasets. This would facilitate that.

### PR DESCRIPTION
**Pull request by cjyetman**
- closes #27

### CODE REVIEW

**Comment by jdhoffa** [comment]
I get this error when running locally: 
``` docker
workflow.pacta.dashboard-1  | zip error: Nothing to do! (outputs/data_archive.zip)
```

**Comment by cjyetman** [comment]
> I get this error when running locally:
> 
> ```
> workflow.pacta.dashboard-1  | zip error: Nothing to do! (outputs/data_archive.zip)
> ```

how does one "run locally" now? like, what exactly does that mean?

**Comment by jdhoffa** [comment]
> how does one "run locally" now? like, what exactly does that mean?

I have a `.env` file that contains:
```
analysis_output_dir: /PATH/TO/pacta_analysis_outputs
benchmarks_dir: /PATH/TO/pacta-data/2023Q4
dashboard_data_dir: /PATH/TO/json_assets_outputs 
```

and call:
``` bash
docker compose up --build
```

**Comment by cjyetman** [comment]
> I have a `.env` file that contains:
> 
> ```
> analysis_output_dir: /PATH/TO/pacta_analysis_outputs
> benchmarks_dir: /PATH/TO/pacta-data/2023Q4
> dashboard_data_dir: /PATH/TO/json_assets_outputs 
> ```

hmmm, ok I don't really know how that works and don't see it documented anywhere... I'll try and see if I can run it somehow and maybe get a similar result as to what you're getting

**Comment by jdhoffa** [comment]
And for flavour, when I do this from `main`, I get: 


> > I have a `.env` file that contains:
> > ```
> > analysis_output_dir: /PATH/TO/pacta_analysis_outputs
> > benchmarks_dir: /PATH/TO/pacta-data/2023Q4
> > dashboard_data_dir: /PATH/TO/json_assets_outputs 
> > ```
> 
> hmmm, ok I don't really know how that works and don't see it documented anywhere... I'll try and see if I can run it somehow and maybe get a similar result as to what you're getting

Created a new issue for documentation 😊

**Comment by cjyetman** [comment]
> > if it's happening in an environment that you're sure there are outputs in the directory defined by `output_dir` in the `prepare_pacta_dashboard_data()`, then I'd appreciate some more detail so I can reproduce, because that would definitely be weird
> 
> And for reference, when I run the same thing (same `.env` file and everything) from `main` I get an output directory with expected datasets:
> 
> ```shell
>  lsd  --group-dirs first -A ~/Downloads/test_dashboard_outputs/
>  data_company_bubble.json         data_techexposure_company_companies.json
>  data_emissions.json              data_techexposure_company_portfolio.json
>  data_emissions_pie_bonds.json    data_techmix_sector.json
>  data_emissions_pie_equity.json   data_trajectory_alignment.json
>  data_exposure_stats.json         data_value_pie_bonds.json
>  data_included_table.json         data_value_pie_equity.json
>  data_techexposure.json  
> ```
> 
> and I get an identical output when running from this branch, so the zipping doesn't seem to be happening

ok, I'll have to wait until I can run it the way you're running it because I can't replicate any of that. If I just run the functions themselves without any fancy stuff, they work as expected, which makes me suspect that something is different in that environment with the directories it is pointing or, possibly that the Docker environment is resistant to the function making a temp directory? 🤷🏻

**Comment by jdhoffa** [comment]
We can pair and have a look tomorrow

**Review by jdhoffa — APPROVED** [review]

**Pull request merged**
