### PR TITLE
prepare company data

### LINKED ISSUE #9: feat: make company-level data filterable on scenario source, scenario and portfolio allocation
Once the company-level plots and data are implemented in the current shape that exists in the interactive report we need to limit the amount of filtering that is done in the respective `prep_*.R` functions so that the users can decide on scenario source, scenario and portfolio allocation themselves. Currently all these choices are done for the user by us. See relevant functions from `pacta.portfolio.report` for reference:

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_company_bubble.R
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/R/prep_key_bars_company.R

FYI @jdhoffa 

AB#11688

### PR DESCRIPTION
**Pull request by cjyetman**
- closes #9

### CODE REVIEW

**Review by jdhoffa — DISMISSED** [review]
woohoo, looks good to me!

**Review by MonikaFu — CHANGES_REQUESTED** [review]
Thank you for all the work so far! I investigated the two datasets created and they look like what we need! We're missing prep function that prepares a dataset called `data_techexposure_company_portfolio.json` though. I know this is confusing but the techmix company plot is the only one that requires two datasets instead of one. There is `*_company` one and there is `*_portfolio` one.

**Comment by cjyetman** [comment]
> Thank you for all the work so far! I investigated the two datasets created and they look like what we need! We're missing prep function that prepares a dataset called `data_techexposure_company_portfolio.json` though. I know this is confusing but the techmix company plot is the only one that requires two datasets instead of one. There is `*_company` one and there is `*_portfolio` one.

@MonikaFu any idea how this was created? [data_techexposure_company_portfolio.json](https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/main/src/json/data_techexposure_company_portfolio.json)

**Review by jdhoffa — APPROVED** [review]

**Comment by jdhoffa** [comment]
Approved, but leave it to @MonikaFu to validate that it works as expected.

**Comment by cjyetman** [comment]
Think I need @AlexAxthelm's approval to merge

**Comment by jdhoffa** [comment]
😈 MUAHAHAHAHAHA

**Pull request merged**
